version: "3"
services:
  db:
    image: postgres:latest
    container_name: searchlight_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - tunnel
  web_app:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - CHARTMETRIC_REFRESH_TOKEN=${CHARTMETRIC_REFRESH_TOKEN}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - app_storage:/rails/storage
    depends_on:
      - db
    ports:
      - "4000:3000"
    networks:
      - tunnel
  cable:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - cable:/data
    networks:
      - tunnel

volumes:
  postgres_data: {}
  app_storage: {}
  cable: {}

networks:
  tunnel:
    name: tunnel
    driver: bridge
