databases:
  - name: postgres
    region: frankfurt
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    region: frankfurt
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SEARCHLIGHT_DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
    region: frankfurt
